version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    labels:
      - "dependencies"
